version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: devops-terminal-backend
    ports:
      - "3001:3001"
    environment:
      - SSH_HOST=localhost
      - SSH_PORT=22
      - SSH_USERNAME=user
      - SSH_PASSWORD=pass
    networks:
      - web-terminal-network

  frontend:
    build:
      context: ./frontend  # Use frontend as the build context
    container_name: devops-terminal-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
      - REACT_APP_WS_URL=ws://backend:3001/ws
    networks:
      - web-terminal-network

  nginx:
    image: nginx:alpine
    container_name: devops-terminal-nginx
    ports:
      - "8081:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # Map frontend nginx.conf to nginx container
      - ./frontend/build:/usr/share/nginx/html/build  # Map frontend build output to nginx
    depends_on:
      - frontend
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    networks:
      - web-terminal-network

networks:
  web-terminal-network:
    driver: bridge

